version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    workingdirectory: ~/switch-controll-manager
    steps:
      - run:
          name: Install JDK
          command: |
            apk --update add openjdk8
            gcloud components install app-engine-java

      - checkout

      - run:
          name: Build
          command: |
            echo "$GCP_SERVICE_ACCOUNT_KEY_TEST" | base64 -d > "$HOME/gcp-service-account-key.json"
            export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-service-account-key.json
            ./mvnw package

      - deploy:
          name: Deploy
          command: |
            if ["$CIRCLE_BRANCH" = "release"]; then
              echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 -d > "$HOME/gcp-service-account-key.json"
              gcloud auth activate-service-account --key-file "$HOME/gcp-service-account-key.json"
              mvnw appengine:deploy
            fi